name: 04 - Using Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # set the working directory for all the steps for running the actions
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    # checkout the code from the repository
    # install dps of our react applications
    # execute automated tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: run tests
        run: npm test
